# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 81a3eeb943461ddc2acd757d4638cddf81dd6e057589ba0c8773e0acdea408fc5d52649831508d47995104da72976936877bd34e309186ae722f45aeb6701fa1

test:
  secret_key_base: ca7f553b8bcce5e7d4eabcbaed31b747fabbe52d5bc00cce93f835480424e5618ec2ec2b368a3fa2d2ad114488202f500f306773badf04c761f0c2d9edfb3d7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
